[phases.setup]
nixPkgs = [
	"nodejs",
	"python3",
	"pkg-config",
	"cairo",
	"pango",
	"libjpeg",
	"giflib",
	"gnumake",
	"gcc",
	"sqlite",
	"pnpm",
]

[phases.install]
cmds = [
	"npm install -g corepack@latest && corepack enable",
	"pnpm i --frozen-lockfile"
]
