# This is a basic workflow to help you get started with Actions

name: Discord Updates

on: [push]

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - name: Run Discord Webhook
      uses: ItsThisTim/classic-discord-webhook
      with:
        id: ${{ secrets.DISCORD_WEBHOOK_ID }}
        token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
