# This is a basic workflow to help you get started with Actions

name: Discord Updates

on: [push]

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - name: Run Discord Webhook
      uses: Mist3r-Robot/discord-webhook@master
      with:
        id: ${{ secrets.DISCORD_WEBHOOK_ID }}
        token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
